
model_params:
  model_type: glow
  num_resnet_blocks: 1 # this will be ignored in glow
  num_scales: 3 #L split happens after each scale
  num_step_of_flow: 22 # K each flow step has 6 affine coupling layers
  n_bins:  265

train_params:
  lr: 1.e-3
  epochs: 100
  model_checkpoint_path: "./model_checkpoints/"

data_params:
  num_samples: -1
  batch_size: 128
  num_workers: 8
  dataset_name: CelebA # CelebA or lsun_bedroom

sampling_params:
  num_samples_nrow: 5
  num_samples_ncols: 5
  generate_fixed_images: True
  samples_output_path: ./samples/glow_CelebA_64*64_L3_K22